### ISSUE TITLE
Support parsing TS enums

### ISSUE THREAD

**Issue by Jpadilla1** [statelyai/xstate-parser#8]
<img width="1673" alt="Screen Shot 2021-09-09 at 1 17 05 PM" src="https://user-images.githubusercontent.com/3780146/132792169-bcc7f457-bf38-4ad0-bcf3-cc5a2b10fa2a.png">

**Comment by mattpocock** [comment]
@Jpadilla1 Added in latest version of VSCode extension, 1.2.1

**Comment by mattpocock** [comment]
Try it here: https://xstate-parser-example-site.vercel.app/
